typeset -gr _SHELL_TO_CHROME_ENFORCED_ZDOTDIR="$SHELL_TO_CHROME_ZSH_POLICY_DIR"
typeset -gr _SHELL_TO_CHROME_ENFORCED_SSH_WRAPPER_DIR="$SHELL_TO_CHROME_SSH_WRAPPER_DIR"
typeset -gr _SHELL_TO_CHROME_USER_ZDOTDIR="${SHELL_TO_CHROME_ORIGINAL_ZDOTDIR:-$HOME}"
source "$_SHELL_TO_CHROME_ENFORCED_ZDOTDIR/apply.zsh" .zshenv
